<a href="https://colab.research.google.com/github/choivxcz/Cuerdo-CSST101-CS3B/blob/main/Exer3_CourseEnrollment_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create Database

In [2]:
students <- data.frame(
  Student_ID = c("S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008"),
  Programming_Grade = c(88, 72, 91, 78, 65, 85, 74, 82),
  Math_Grade = c(85, 70, 88, 80, 68, 90, 73, 79),
  Attendance = c(92, 80, 95, 88, 70, 91, 76, 85),
  Prerequisite = c("Yes", "No", "Yes", "Yes", "No", "Yes", "No", "Yes")
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes

2.Explore the data

In [3]:
nrow(students)
ncol(students)

max(students["Programming_Grade"])
max(students["Math_Grade"])
max(students["Attendance"])
mean(students$Programming_Grade)
mean(students$Math_Grade)
mean(students$Attendance)
min(students["Attendance"])
min(students["Math_Grade"])
min(students["Attendance"])
sum(students["Attendance"])
sum(students["Math_Grade"])
sum(students["Attendance"])
length(students)

[1] 8

[1] 5

[1] 91

[1] 90

[1] 95

[1] 79.375

[1] 79.125

[1] 84.625

[1] 70

[1] 68

[1] 70

[1] 677

[1] 633

[1] 677

[1] 5

3. Enter Student ID

In [4]:
student_id <- readline("Enter Student ID: ")
print(student_id)

Enter Student ID: S001
[1] "S001"

4. Search the dataframe

In [5]:
student <- students[
  students$Student_ID == student_id,
]

student

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes

5. Check if students exist

```
# This is formatted as code
```

In [6]:
if (nrow(student) > 0) {
  print("Student exists")
  print(student)
} else {
  print("Student does not exist")
}

[1] "Student exists"
  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1       S001                88         85         92          Yes

6. Extract student information

In [7]:
programming <- student$Programming_Grade
math <- student$Math_Grade
attendance <- student$Attendance
stud_ID <- student$Student_ID
preq <- student$Prerequisite
cat("Student ID:", stud_ID)
cat("\nProgramming Grade:", programming)
cat("\nMath Grade:", math)
cat("\nAttendance:", attendance)
cat("\nPrerequisite:", preq)

Student ID: S001
Programming Grade: 88
Math Grade: 85
Attendance: 92
Prerequisite: Yes

7. Implement the rules

In [8]:
student_eligibility <- function(programming, math, attendance, prerequisite)
if (programming >= 80 && math >= 75 && attendance >= 80 && prerequisite == "Yes"){
  print("Eligible")
}else if (programming >= 75 && math >= 70 && attendance >= 75){
  print("Conditionally Elibible")
}else{
 print("Not Eligible")
}

student_eligibility(78,87,54,"No")

[1] "Not Eligible"

8. Apply the function to all students

In [9]:
students$Eligibility <- mapply(
  student_eligibility,
  students$Programming_Grade,
  students$Math_Grade,
  students$Attendance,
  students$Prerequisite
)

[1] "Eligible"
[1] "Not Eligible"
[1] "Eligible"
[1] "Conditionally Elibible"
[1] "Not Eligible"
[1] "Eligible"
[1] "Not Eligible"
[1] "Eligible"

9. Create Recommendation Rules

In [10]:
get_recommendation <- function(eligibility) {

  if (eligibility == "Eligible") {
    return("Student may Enroll")

  } else if (eligibility == "Conditional Eligible") {
    return("Consult Academic Adviser")

  } else {
    return("Complete requirements before enrollment")
  }
}

students$Recommendation <- sapply(
  students$Eligibility,
  get_recommendation
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Eligibility            Recommendation
1 Eligible               Student may Enroll
2 Not Eligible           Complete requirements before enrollment
3 Eligible               Student may Enroll
4 Conditionally Elibible Complete requirements before enrollment
5 Not Eligible           Complete requirements before enrollment
6 Eligible               Student may Enroll
7 Not Eligible           Complete requirements before enrollment
8 Eligible               Student may Enroll

10. Course Enrollment Adviser

In [11]:
student_id <- readline(prompt = "Enter Student ID: ")

student <- students[students$Student_ID == student_id, ]

if (nrow(student) > 0) {

  cat("\n========================================\n")
  cat("       COURSE ENROLLMENT ADVISER\n")
  cat("========================================\n\n")

  cat("Student ID:", student$Student_ID, "\n\n")

  cat(sprintf("Programming Grade: %.2f%%\n", student$Programming_Grade))
  cat(sprintf("Math Grade: %.2f%%\n", student$Math_Grade))
  cat(sprintf("Attendance: %.2f%%\n", student$Attendance))
  cat("Prerequisite:", student$Prerequisite, "\n\n")

  cat("Enrollment Status:\n")
  cat(student$Eligibility, "\n\n")

  cat("Recommendation:\n")
  cat(student$Recommendation, "\n")

  cat("========================================\n")

} else {
  cat("\nStudent ID not found.\n")
}

Enter Student ID: S001

========================================
       COURSE ENROLLMENT ADVISER
========================================

Student ID: S001

Programming Grade: 88.00%
Math Grade: 85.00%
Attendance: 92.00%
Prerequisite: Yes

Enrollment Status:
Eligible

Recommendation:
Student may Enroll
========================================